core/urls.py
from django.urls import include, path
from core.views import *

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    # path("<cat_title>/", category, name="category"),
    path("category/<str:cate_slug>/", category, name="inner-category"),
    path("shop-category/<str:main_slug>/", main_category, name="main_category"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path("cart/", cart_view, name="cart_view"),
    path("product/<slug:product_slug>/", product, name="product"),
    path("product/<title>/", producttitle, name="producttitle"),
    path("search/", search_view, name="search"),
    path("delete-from-cart/", delete_item_from_cart, name="delete-from-cart"),
    path("update-cart/", update_cart, name="update-cart"),
    path("checkout/", checkout_view, name="checkout"),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path("payment-failed/", payment_failed_view, name="payment-failed"),
    path("architectures/", arch, name="arch"),
    path("architectures/<name>/", arch_name, name="arch_name"),
    path("builder/", build, name="build"),
    path("builder/<name>/", build_name, name="build_name"),
    path("about-us/", about, name="about-us"),
    path("dashboard/", dashboard, name="dashboard"),
    path("dashboard/myorders/", orders, name="orders"),
    path('dashboard/myorders/<int:order_id>/invoice/', generate_user_invoice, name='user_generate_invoice'),
    path("our-reviews/", our_reviews, name="our-reviews"),
    path("our-clients/", our_clients, name="our-clients"),
    path("our-achievements/", our_achievements, name="our-achievements"),
    path("premium-websites/", premium_websites, name="premium-websites"),
    path("our-works/", our_works, name="our_works"),
    path("our-media/", our_media, name="our_media"),
    path("thankyouorder/", thankyouorder, name="thankyouorder"),
    path('fetch-pin-details/', fetch_pin_details, name='fetch_pin_details'),
    path("blog_details/<blog_slug>/", blog_details, name="blog_details"),
    path("contact-us/", contact, name="contact-us"),
    path("career", career, name="career"),
    path("write-to-ceo/", write_to_ceo, name="write_to_ceo"),
    path("blog/", blogs, name="blogs"),
    path("testing/", testing, name="testing"),
    path("payment-invoice/", payment_invoice, name="payment_invoice"),
    path("download_invoice/", download_invoice, name="download_invoice"),
    # path("payment-invoicee/", payment_invoicee, name="payment_invoicee"),
    path("privacy-policy/", privacypolicy, name="privacypolicy"),
    path("<slug:sub_cat_slug>/", sub_category, name="sub-category"),
]

ecomproj/urls.py
from django.contrib import admin
from django.urls import path, include
from tinymce import urls as tinymce_urls
from django.contrib.sitemaps.views import sitemap
from core.sitemap import *
from core.views import RobotsTxtView
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'main_category': MainCategorySitemap,
    'category': CategorySitemap,
    'sub_category': SubCategorySitemap,
    'product': ProductSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', RobotsTxtView.as_view(), name='robots_txt'),
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User


class ExportCartOrdersForm(forms.Form):
    start_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    end_date = forms.DateField(required=False, widget=forms.TextInput(attrs={'type': 'date'}))
    paid_status = forms.ChoiceField(
        choices=[
            ('', 'All'),  # Allowing all options
            ('True', 'Paid'),
            ('False', 'Unpaid')
        ],
        required=False
    )

core/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string
from core.models import *
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import Http404
import os
import requests
from django.db.models import Case, When, Value, IntegerField
from django.views.generic import View
import razorpay
from django.db import transaction
from decimal import Decimal, InvalidOperation
from datetime import datetime 
from decimal import Decimal, ROUND_HALF_UP
import re
from django.http import QueryDict
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags    
from num2words import num2words
from bs4 import BeautifulSoup
from indian_pincode_details import get_pincode_details
import indiapins
import json
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from xhtml2pdf import pisa
from io import BytesIO


def index(request):
    product = Main_category.objects.all()
    walpaper_cat = Company_name.objects.filter(wallpaper_category=True)
    curtain_sofa_brands = Company_name.objects.filter(curtain_sofa_brands=True)
    mattresses_brands = Company_name.objects.filter(mattresses_brands=True)
    window_blind_brands = Company_name.objects.filter(window_blinds_brands=True)
    carpet_tile_office = Company_name.objects.filter(carpet_tile_for_office_brands=True)
    rugs_brands = Company_name.objects.filter(rugs_brands=True)
    pillow_brands = Company_name.objects.filter(pillow_brands=True)
    hospital_floor_walls = Company_name.objects.filter(hospital_walls_brands=True)
    wooden_laminate = Company_name.objects.filter(wooden_laminate_flooring_brands=True)
    pvc_rubber = Company_name.objects.filter(pvc_rubber_flooring_brands=True)
    curtain_rods_channel = Company_name.objects.filter(curtains_rods_channel_brands=True)
    foam_material = Company_name.objects.filter(foam_material_brands=True)
    awning_canopy = Company_name.objects.filter(awning_canopy_brands=True)


    context = {
        "main_cat":product,
        "walpaper_cat": walpaper_cat,
        "curtain_sofa_brands": curtain_sofa_brands,
        "mattresses_brands": mattresses_brands,
        "window_blind_brands": window_blind_brands,
        "carpet_tile_office": carpet_tile_office,
        "rugs_brands": rugs_brands,
        "pillow_brands": pillow_brands,
        "hospital_floor_walls": hospital_floor_walls,
        "wooden_laminate": wooden_laminate,
        "pvcrubber": pvc_rubber,
        "curtain_rods_channel": curtain_rods_channel,
        "foam_material": foam_material,
        "awning_canopy": awning_canopy,
    }
    return render(request, 'core/index.html', context)

def category(request, cate_slug):
    category = get_object_or_404(Category, cate_slug=cate_slug)
    company_names = Company_name.objects.filter(category=category)
    
    # Fetch all sub-categories related to the category
    all_sub_categories = Sub_categories.objects.filter(category=category)

    # Specify the desired order for "Wallpapers" sub-categories
    wallpaper_order = ['SABYASACHI', 'Versace', 'Dolce & Gabbana', 'Lamborghini', 'Good Earth', 'Philipp Plein', 'Trussardi', 'Roberto Cavalli', 'Cole & Sons', 'Tailor Weave by Burberry', 'Customization', 'Deluxe', 'Economic']

    # Conditionally order sub-categories based on the category
    sub_categories = all_sub_categories.order_by(
        Case(
            *[When(sub_cat_title=title, then=pos) for pos, title in enumerate(wallpaper_order)],
            default=Value(999),  # Default value for other sub-categories (alphabetical order)
            output_field=IntegerField()
        )
    )

    # Fetch related products using the relationships
    products = Product.objects.filter(
        category=category,
        sub_category__in=all_sub_categories,
        company_name__in=company_names
    )

    context = {
        "category": category,
        "company_names": company_names,
        "sub_categories": sub_categories,
        "products": products,
    }

    return render(request, "core/category.html", context)


def sub_category(request, sub_cat_slug):
    sub_cats = Sub_categories.objects.filter(slug=sub_cat_slug)

    if not sub_cats.exists():
        # Handle the case where no objects are found
        raise Http404("Sub-category does not exist")

    sub_cat = sub_cats.first()

    related_sub_categories = Sub_categories.objects.filter(maincat=sub_cat.maincat, category=sub_cat.category)
    company_names = Company_name.objects.filter(sub_category=sub_cat)
    
    # Create a dictionary to store company names and their associated products
    company_products = {}
    for company in company_names:
        products = Product.objects.filter(company_name=company)
        company_products[company] = products

    # Fetch sub-categories images
    sub_cat_images = SubcategoryImages.objects.filter(sub_category=sub_cat)
    image_urls = [image.images.url for image in sub_cat_images]

    context = {
        "sub_cat": sub_cat,
        "company_products": company_products,
        "related_sub_categories": related_sub_categories,
        "sub_cat_images": sub_cat_images,
        "image_urls": image_urls,
    }

    return render(request, "core/sub-category.html", context)



def main_category(request, main_slug):
    main_categories = get_object_or_404(Main_category, main_slug=main_slug)
    categories = Category.objects.filter(main_category=main_categories)

    context = {
        "main_categories": main_categories,
        "categories": categories,
    }
    return render(request, "core/main_category.html", context)

def fetch_pin_details(request):
    if request.method == 'GET':
        zipcode = request.GET.get('zipcode')
        print('Zipcode received:', zipcode)
        
        pin_details_list = indiapins.matching(zipcode)
        print('Pin details fetched:', pin_details_list)
        
        if pin_details_list:
            # Format all pin details to be sent in the response
            response_data = [
                {
                    'Name': pin_details.get('Name'),
                    'Region': pin_details.get('Region'),
                    'District': pin_details.get('District'),
                    'Division': pin_details.get('Division'),
                    'Block': pin_details.get('Block'),
                    'Circle': pin_details.get('Circle'),
                    'State': pin_details.get('State')
                }
                for pin_details in pin_details_list
            ]
            response = {
                'success': True,
                'data': response_data
            }
            print('Response:', response)  # Check if the response is correctly formatted
            return JsonResponse(response)
        else:
            return JsonResponse({'success': False, 'error': 'Pincode details not found'})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})




def add_to_cart(request):
    # Ensure all required parameters are present
    required_params = ['id', 'title', 'qty', 'price', 'image', 'sku', 'price_wo_gst', 'gst_rate', 'gst_applied']
    for param in required_params:
        if param not in request.GET:
            return JsonResponse({"error": f"Missing parameter: {param}"}, status=400)

    product_id = request.GET.get('id')
    sku = request.GET.get('sku')
    price = request.GET.get('price')

    # Create a more unique key by including sku and price
    unique_key = f"{product_id}_{sku}_{price}" 

    try:
        qty = int(request.GET['qty'])  # Ensure qty is an integer
    except ValueError as e:
        return JsonResponse({"error": f"Invalid numeric value for qty: {str(e)}"}, status=400)

    try:
        price = Decimal(request.GET['price'])  # Ensure price is a decimal
    except InvalidOperation as e:
        return JsonResponse({"error": f"Invalid numeric value for price: {str(e)}"}, status=400)

    try:
        price_wo_gst = Decimal(request.GET['price_wo_gst'])  # Ensure price_wo_gst is a decimal
    except InvalidOperation as e:
        return JsonResponse({"error": f"Invalid numeric value for price_wo_gst: {str(e)}"}, status=400)

    try:
        gst_rate = Decimal(request.GET['gst_rate'])  # Ensure gst_rate is a decimal
    except InvalidOperation as e:
        return JsonResponse({"error": f"Invalid numeric value for gst_rate: {str(e)}"}, status=400)
    
    try:
        gst_applied = Decimal(request.GET['gst_applied'])  # Ensure gst_applied is a decimal
    except InvalidOperation as e:
        return JsonResponse({"error": f"Invalid numeric value for gst_applied: {str(e)}"}, status=400)

    cart_product = {
        'product_id': product_id,
        'title': request.GET.get('title'),
        'qty': qty,
        'price': str(price),  # Convert Decimal to string
        'image': request.GET.get('image'),
        'sku': sku,
        'price_wo_gst': str(price_wo_gst),  # Convert Decimal to string
        'gst_rate': str(gst_rate),  # Convert Decimal to string
        'gst_applied': str(gst_applied),  # Convert Decimal to string
    }

    if 'cart_data_obj' in request.session:
        cart_data = request.session['cart_data_obj']
        # Check if the product with the same unique key is already in the cart
        if unique_key in cart_data:
            return JsonResponse({"already_in_cart": True})
        
        cart_data[unique_key] = cart_product
    else:
        cart_data = {unique_key: cart_product}

    request.session['cart_data_obj'] = cart_data

    return JsonResponse({

templates/core/change_list.html
{% extends 'admin/change_list.html' %}
{% load i18n %}

{% block object-tools %}
    {{ block.super }}
    <ul class="object-tools-items">
        <li>
            <form method="get" action="{% url 'admin:export_cart_orders_csv' %}" style="display: inline;">
                <input type="date" name="start_date">
                <input type="date" name="end_date">
                <select name="paid_status">
                    <option value="">{{ _('All') }}</option>
                    <option value="True">{{ _('Paid') }}</option>
                    <option value="False">{{ _('Unpaid') }}</option>
                </select>
                <button type="submit" class="button btn btn-primary">{{ _('Download Cart Orders') }}</button>
            </form>
        </li>
    </ul>
{% endblock %}

templates/core/main_category.html
{% extends 'partials/base.html' %}
{% load static %}
{% block breadmb %}
<div id="page-title-bar" class="page-title-bar page-title-bar-minimal-01">
  <div class="page-title-bar-inner">
    <div class="page-title-bar-bg"></div>

    <div id="page-breadcrumb" class="page-breadcrumb">
      <div class="container-broad">
        <div class="page-breadcrumb-wrap">
          <ul class="insight_core_breadcrumb">
            <li class="level-1 top item-home">
              <a href="/">Home</a>
            </li>
            <li class="level-2 sub item-current tail current">
                <span>{{main_categories.main_title}}</span>
              </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock breadmb %} 

{% block content %}
<div id="page-content" class="page-content">
  <div class="container-broad">
    <div class="row">
      <div class="page-sidebar page-sidebar-left sidebar-primary">
        <div
          class="page-sidebar-inner tm-sticky-column"
          data-sticky-group="content-sidebar"
          itemscope="itemscope"
        >
          <a href="#" class="btn-close-off-sidebar">
            <svg
              width="18"
              height="18"
              viewBox="0 0 18 18"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M10.6465 8.975L16.7012 15.0297C16.8639 15.1924 16.8639 15.3715 16.7012 15.5668L15.5781 16.6898C15.3828 16.8526 15.2038 16.8526 15.041 16.6898L14.0156 15.6156L8.98633 10.6352L2.93164 16.6898C2.76888 16.8526 2.58984 16.8526 2.39453 16.6898L1.27148 15.5668C1.10872 15.3715 1.10872 15.1924 1.27148 15.0297L7.32617 8.975L1.27148 2.92031C1.10872 2.75755 1.10872 2.57852 1.27148 2.3832L2.39453 1.26016C2.58984 1.0974 2.76888 1.0974 2.93164 1.26016L8.98633 7.31484L15.041 1.26016C15.2038 1.0974 15.3828 1.0974 15.5781 1.26016L16.7012 2.3832C16.8639 2.57852 16.8639 2.75755 16.7012 2.92031L15.627 3.9457L10.6465 8.975Z"
                fill="#000000"
              />
            </svg>
          </a>
          <div class="page-sidebar-content-wrap">
            <div class="page-sidebar-content"></div>
          </div>
        </div>
      </div>

      <div class="page-main-content">
        <div id="dokan-store-tabs-wrap" class="dokan-store-tabs-wrap"></div>

        <div class="dokan-store-wrap layout-left">
          <div id="dokan-primary" class="dokan-single-store">
            <div
              id="dokan-content"
              class="store-page-wrap woocommerce"
              role="main"
            >
              <div class="seller-items">
                <div
                  id="minimog-main-post"
                  class="minimog-main-post minimog-grid-wrapper minimog-product group-style-06 style-grid-06 caption-style-06"
                  data-grid='{"type":"grid","columns":"4","columnsTabletExtra":"3","columnsMobileExtra":"2","gutter":"30","gutterTabletExtra":"20","gutterMobileExtra":"16"}'
                  style="
                    --grid-columns-desktop: 4;
                    --grid-columns-tablet-extra: 3;
                    --grid-columns-mobile-extra: 2;
                    --grid-gutter-desktop: 30;
                    --grid-gutter-tablet-extra: 20;
                    --grid-gutter-mobile-extra: 16;
                  "
                >
                  <div class="minimog-grid lazy-grid">
                    <div class="grid-sizer"></div>
                   {% for main in categories %}
                    <div
                      class="grid-item product type-product post-987 status-publish instock product_cat-dishwashers product_tag-dishwasher has-post-thumbnail shipping-taxable purchasable product-type-variable has-default-attributes vi-sctv-product"
                    >
                      <div class="product-wrapper">
                        <div class="product-thumbnail">
                          <div class="thumbnail">
                            <a
                              href="{% url 'core:inner-category' main.cate_slug %}"
                              class="woocommerce-LoopProduct-link woocommerce-loop-product__link"
                            >
                              <div class="product-main-image">
                                <div
                                  class="minimog-lazy-image"
                                  style="
                                    --lazy-image-width: 450px;
                                    --lazy-image-height: 100%;
                                  "
                                >
                                  <img
                                    src="data:image/svg+xml;charset=utf8,%3Csvg%20xmlns%3D%22http://www.w3.org/2000/svg%22%20viewBox%3D%220%200%20450%20450%22%3E%3C%2Fsvg%3E"
                                    width="450"
                                    height="450"
                                    alt=""
                                    data-src="{{main.image.url}}"
                                    class="product-main-image-img ll-image"
                                  />
                                </div>
                              </div>

                              <div class="product-hover-image">
                                <div
                                  class="minimog-lazy-image"
                                  style="
                                    --lazy-image-width: 450px;
                                    --lazy-image-height: 100%;
                                  "
                                >
                                  <img
                                    src="data:image/svg+xml;charset=utf8,%3Csvg%20xmlns%3D%22http://www.w3.org/2000/svg%22%20viewBox%3D%220%200%20450%20450%22%3E%3C%2Fsvg%3E"
                                    width="450"
                                    height="450"
                                    alt="product_kitchen_2_3"
                                    data-src=""
                                    class="ll-image"
                                  />
                                </div>
                              </div>
                            </a>
                          </div>
                        </div>

                        <div class="product-info">
                          <div class="loop-product-category">
                            <a
                              href=""
                            >
                            {{main_categories.main_title}}
                            </a>
                          </div>

                          <h3
                            class="woocommerce-loop-product__title post-title-2-rows"
                          >
                            <a
                              href="{% url 'core:inner-category' main.cate_slug %}"
                              >  {{main.cat_title}}</a
                            >
                          </h3>

                          

                       

                          <div class="content-view-list">
                            <div
                              class="woocommerce-loop-product__desc post-title-2-rows"
                            >
                             
                            </div>

                            <div class="product-list-view-actions">
                              <div
                                class="product-action hint--bounce hint--top woocommerce_loop_add_to_cart_wrap"
                                data-hint="Select options"
                              >
                                <a
                                  href="{% url 'core:inner-category' main.cate_slug %}"
                                  data-quantity="1"
                                  class="button wp-element-button product_type_variable add_to_cart_button"
                                  data-product_id="987"
                                  data-product_sku=""
                                  aria-label="Select options for &ldquo;Built-in dishwasher, Stainless steel Essentiell&rdquo;"
                                  rel="nofollow"
                                  ><span>View Products</span></a
                                >
                              </div>
                              <div
                                class="product-action wishlist-btn style-01 icon-star hint--bounce hint--top"
                                data-hint="Add to wishlist"
                              >
                                <a
                                  href="?add-to-wishlist=987"
                                  class="woosw-btn woosw-btn-987"
                                  data-id="987"
                                  data-product_name="Built-in dishwasher, Stainless steel Essentiell"
                                  data-product_image=""
                                  >Add to wishlist</a
                                >
                              </div>
                              <div
                                class="product-action compare-btn style-01 hint--bounce hint--top"
                                data-hint="Compare"
                              >
                                <a
                                  href="?add-to-compare=987"
                                  class="woosc-btn woosc-btn-987"
                                  data-id="987"
                                  data-product_name="Built-in dishwasher, Stainless steel Essentiell"
                                  data-product_image=""
                                  >Compare</a
                                >
                              </div>
                              <div
                                class="product-action quick-view-btn style-01 hint--bounce hint--top"
                                data-hint="Quick view"
                                data-pid="987"
                              >
                                <a class="quick-view-icon" href="#"
                                  >Quick view</a
                                >
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="background-color-expand">
                        <div
                          class="product-action hint--bounce hint--top woocommerce_loop_add_to_cart_wrap"
                          data-hint="Select options"
                        >
                          <a
                            href="{% url 'core:inner-category' main.cate_slug %}"
                            data-quantity="1"
                            class="button wp-element-button product_type_variable add_to_cart_button"
                            data-product_id="987"
                            data-product_sku=""
                            aria-label="Select options for &ldquo;Built-in dishwasher, Stainless steel Essentiell&rdquo;"
                            rel="nofollow"
                            ><span>View Products</span></a
                          >
                        </div>
                      </div>
                    </div>
                    {% endfor %}
                 



                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- .dokan-single-store -->
        </div>
        <!-- .dokan-store-wrap -->
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/core/privacy-policy.html
{% extends 'partials/base.html' %} {% load static %} 
{% block breadmb %}
<div id="page-title-bar" class="page-title-bar page-title-bar-minimal-01">
  <div class="page-title-bar-inner">
    <div class="page-title-bar-bg"></div>

    <div id="page-breadcrumb" class="page-breadcrumb">
      <div class="container-broad">
        <div class="page-breadcrumb-wrap">
          <ul class="insight_core_breadcrumb">
            <li class="level-1 top item-home">
              <a href="/">Home</a>
            </li>
            <li class="level-2 sub item-current tail current">
              <span>Privacy Policy</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock breadmb %}

{% block content %}
<section class="elementor-section elementor-top-section elementor-element elementor-element-18fd70a elementor-section-boxed elementor-section-gap-beside-yes elementor-section-height-default elementor-section-height-default elementor-section-column-vertical-align-stretch" data-id="18fd70a" data-element_type="section">
  <div class="elementor-container elementor-column-gap-extended">
    <div class="elementor-row">
      <div class="elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-b521ef3" data-id="b521ef3" data-element_type="column">
        <div class="elementor-column-wrap elementor-element-populated">
          <div class="elementor-widget-wrap" style="text-align: center;">
            <div class="elementor-element elementor-element-0650558 elementor-widget elementor-widget-tm-heading" data-id="0650558" data-element_type="widget" data-widget_type="tm-heading.default">
              <div class="elementor-widget-container">
                <div class="tm-modern-heading tm-modern-heading--style-01 tm-modern-heading--highlight-style-01">
                  <div class="heading-primary-wrap">
                    
                   
                  </div>
                </div>
              </div>
            </div>
            <style>
              .faq-toggle {
background: linear-gradient(90deg, #e6317b, #bd529c, #6b94ce);
-webkit-background-clip: text;
color: transparent;
display: inline;
}

.faq-answer{
padding-top: 1.8rem;
padding-bottom: 2rem ;
}

            </style>
            <div class="elementor-element elementor-element-faq-content" data-id="faq-content" data-element_type="widget">
              <div class="elementor-widget-container">
    
                <div class="faq-question">
                  <div class="faq-answer">
                      {{ privacy_policy_content | safe }}
                  </div>
              </div>

                <!-- Add more FAQ items as needed -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}